### ISSUE TITLE
Nothing to happen when click on the 'Add story' button.

### ISSUE THREAD

**Issue by kanekoh** [Codeminer42/cm42-central#188]
Tried to build cm42-central from scratch with docker-compose on Windows 10.

After applying instruction which @alceumedeiros suggested, I could create a project on cm42-central.
However, nothing to happen when I clicked on the 'Add story' button. 

I checked cm42 log messages during clicking the button but no log messages appeared.

I had no any changes in my .env and config/database.yml files, just using default values and logged in cm42 with `foo@bar.com`.

What do I need to setup parameters for enabling a button?

The below is my environment.

- Docker for Windows: docker-compose version 1.11.2, build f963d76f
- cm42-central: using latest master branch source code.

and followings are .evn and config/database.yml files contents.

#### .env

```
CLOUDINARY_URL=cloudinary://username:password@localhost
MAILER_SENDER=noreply@localhost
MAIN_HOST=localhost:3000
MEMCACHIER_SERVERS=localhost:11211
SECRET_TOKEN=392bed61219db525f689555601bd40b3f12f8c7d06cbe73323d069b104272c4c0a91cc5acf1c0fc0e9b78482e5dde21a2770f82ab10af08d5de678170c6fd727
SECRET_KEY_BASE=1ed0f0a41f719a95c1bad446e9960090cd6e2a5c5f212b7a5cfe1b582548f2a3d4b78f16b99f3883713d71c87b7642537a3a579d522363d285377b1f206fc4ce
STORIES_CEILING=300
CDN_URL=http://xpto.cloudfront.net
NEW_RELIC_LICENSE_KEY=your_license_key
INTEGRATION_URI_MATTERMOST=http://foo.com
RECAPTCHA_PUBLIC_KEY=
RECAPTCHA_PRIVATE_KEY=
WEBPACK_HOST="0.0.0.0"
WEBPACK_MANIFEST_HOST="localhost"
WEBPACK_MANIFEST_PORT="3808"
WEBPACK_PORT="3808"
DB_USERNAME=
DB_PASSWORD=
DB_HOST=
```

#### config/database.yml

```
# PostgreSQL
base: &base
  host: <%= ENV['DB_HOST'] %>
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *base
  database: fulcrum_development

test:
  <<: *base
  database: fulcrum_test

production:
  <<: *base
  database: fulcrum_production
```

Thanks in advance.
